/*
 * Copyright 2026 RuLei Chen
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "post_args.h"

#include <argparse.h>

#include "cli/cli_helper.h"

void setup_post_args(argparse::ArgumentParser& cmd)
{
    cmd.add_description(
        "MCMC posterior analysis: diagnostics (ESS, R-hat, HPDI) from fit "
        "output");

    cmd.add_group("Input");
    cmd.add_argument("--in")
        .help(
            "Fit output prefix(es), one per chain (reads "
            "{prefix}.scalar_chain)")
        .metavar("<PREFIX>")
        .nargs(argparse::nargs_pattern::at_least_one)
        .required();

    cmd.add_argument("-o", "--out")
        .help("Output file prefix")
        .metavar("<OUT>")
        .default_value("gelex");

    cmd.add_epilog(
        gelex::cli::format_epilog(
            "{bg}Example:{rs}\n"
            "  {bc}gelex post{rs} {cy}--in{rs} run1 run2 run3\n\n"
            "{bg}Note:{rs}\n"
            "  Each prefix must have a corresponding .scalar_chain file\n"
            "  generated by {bc}gelex fit{rs}."));
}
