version: 2

build:
  os: ubuntu-24.04
  apt_packages:
    - librsvg2-bin
  tools:
    python: "3.13"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - pdf
