context:
  name: gelex
  version: "0.9.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: .

build:
  number: 0
  script:
    - |
      cmake $CMAKE_ARGS -G "Ninja" \
        -DGELEX_USE_MKL=ON \
        -DGELEX_BUILD_TESTS=OFF \
        -DGELEX_BUILD_BENCHMARKS=OFF \
        -DGELEX_NATIVE_OPTIMIZATION=OFF \
        -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
        $SRC_DIR
      cmake --build . --parallel
      cmake --install .

requirements:
  build:
    - ${{ compiler('cxx') }}
    - sysroot_linux-64 == 2.17
    - cmake >=3.20
    - ninja
  host:
    - mkl-devel >=2025.3.0
    - spdlog
  run:
    - mkl >=2025.3.0
    - spdlog

tests:
  - package_contents:
      bin:
        - gelex
  - script:
      - gelex --help

about:
  homepage: https://github.com/r1cheu/gelex
  license: Apache-2.0
  summary: High-performance C++ genomic analysis toolkit
  description: |
    GELEX (GEnome LEX) is a high-performance C++ genomic analysis toolkit
    for large-scale genomic prediction and association studies. Features
    Bayesian models (BayesA/B/C/R/RR series), GBLUP with REML, GWAS with
    LOCO support, and GRM computation. Optimized with AVX512/AVX2, OpenMP,
    and MKL/OpenBLAS backend.
