context:
  version: ${{ load_from_file("../VERSION") | trim }}

package:
  name: gelex
  version: ${{ version }}

source:
  path: ..

build:
  number: 0
  script:
    - cmake ${CMAKE_ARGS} -GNinja -B build $SRC_DIR
      -DCMAKE_BUILD_TYPE=Release
      -DGELEX_BUILD_CLI=ON
      -DGELEX_NATIVE_OPTIMIZATION=OFF
      -DCMAKE_INSTALL_PREFIX=$PREFIX

    - cmake --build build
    - cmake --install build --component cli

    - mkdir -p $PREFIX/share/bash-completion/completions
    - $PREFIX/bin/gelex completion bash > $PREFIX/share/bash-completion/completions/gelex
    - mkdir -p $PREFIX/share/fish/vendor_completions.d
    - $PREFIX/bin/gelex completion fish > $PREFIX/share/fish/vendor_completions.d/gelex.fish

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - if: linux
      then: libgomp
      else: llvm-openmp

    - eigen >=5,<6
    - fmt >=12,<12.2
    - spdlog >=1.17,<2
    - cli11 >=2.6,<3
    - libblas * *netlib
    - liblapacke * *netlib
  run:
    - if: linux
      then: libgomp
      else: llvm-openmp

tests:
  - package_contents:
      files:
        exists:
          - bin/gelex
          - share/bash-completion/completions/gelex
          - share/fish/vendor_completions.d/gelex.fish
  - script:
      - gelex --help

about:
  homepage: https://github.com/r1cheu/gelex
  license: Apache-2.0
  license_file: LICENSE
  summary: High-performance genomic analysis toolkit for genomic prediction and association studies
  repository: https://github.com/r1cheu/gelex
